using API.ArticleCore.Models;

namespace API.ArticleCore.Events
{
    public class ArticleCreatingEventArgs : EventArgs
    {
        public int ArticleId { get; set; }

        /// <summary>
        /// Unmodified incoming data.
        /// </summary>
        /// <remarks>
        /// The model is not modified after save, so autogenerated fields (such as Id) will not be updated from the original values passed in.
        /// </remarks>
        public IArticleModel SaveData { get; set; } = null!;

        public ArticleCreatingEventArgs(int articleId, IArticleModel saveData)
        {
            ArticleId = articleId;
            SaveData = saveData;
        }
    }
}
