namespace APIClient.Constants
{
    public class Roles
    {
        /// <summary>
        /// Manages configs and handles potentially breaking changes.
        /// </summary>
        /// <remarks>
        /// Authorized for all routes.
        /// </remarks>
        public const string Administrator = nameof(Administrator);

        /// <summary>
        /// Reviews and schedules publications.
        /// </summary>
        public const string Editor = nameof(Editor);

        /// <summary>
        /// Notifies of new stories.
        /// </summary>
        public const string Informant = nameof(Informant);

        /// <summary>
        /// Researches and writes articles, cannot publish.
        /// </summary>
        public const string Journalist = nameof(Journalist);

        /// <summary>
        /// Moderates content generated by non-staff.
        /// </summary>
        public const string Moderator = nameof(Moderator);

        /// <summary>
        /// Accesses public data.
        /// </summary>
        public const string Public = nameof(Public);
    }
}
